### ISSUE TITLE
omit { return ...; }

### ISSUE THREAD

**Issue by chris-kruining** [preprocess/pre-short-closures#4]
Is it possible to edit/add a macro that parses a arrow function that omit's the accolades?
ie.
```php
($t, $k, $v) => { return str_replace("{" . $k . "}", $v, $t ); }
```
would become
```php
($t, $k, $v) => str_replace("{" . $k . "}", $v, $t )
```

and when there is only one parameter the `(` and `)` can be omited, i.e.
```php
$key => str_replace(' ', '', $key)
```

**Comment by chris-kruining** [comment]
I would love to add a label 'feature-request' but I don't seem to have those rights :P

**Comment by assertchris** [comment]
Thanks for the suggestion. I'd love to enable these things too, but I'm not sure how I'd go about doing it.

The trouble is that `=>` already has meaning in PHP. If we changed it to another symbol, like `~>` or `→` then it might be easier. In addition, there's no simple way to match an expression, in Yay; so omitting `{` and `}` becomes that much harder.

I think the best we could do (given the current limitations of Yay) is 
`$key → { str_replace(' ', '', $key) }`

Edit: I guess I could work on a custom compiler function, to replace `$foo ~> $bar` with 
`($foo) => { return $bar; }`...

**Comment by assertchris** [comment]
What character would you like?
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXV4S0WHS82ZXR40AKQQ1F1K/-%3E)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXV4S0WHS82ZXR40AKQQ1F1K/-%3E/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXV4S0WHS82ZXR40AKQQ1F1K/%3D%3E)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXV4S0WHS82ZXR40AKQQ1F1K/%3D%3E/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXV4S0WHS82ZXR40AKQQ1F1K/~%3E)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXV4S0WHS82ZXR40AKQQ1F1K/~%3E/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXV4S0WHS82ZXR40AKQQ1F1K/%E2%86%92)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BXV4S0WHS82ZXR40AKQQ1F1K/%E2%86%92/vote)

**Comment by chris-kruining** [comment]
would `==>` be an option?

**Comment by assertchris** [comment]
It could be, but we need the custom compiler function (or a Yay `·expression` matcher) for the optional `{` and `}`. The only thing a new `==>`gives us is an easier path to optional single-parameter parens...

**Comment by chris-kruining** [comment]
hmmm, okay, but I was thinking that the more verbose form (`($foo) => { return $bar; }`) would also then use `==>` to prevent confusion, imho I think that there should be a single operator for short closures, may it be with or without `()` and `{}`. I was hoping it would be possible to achieve es6 arrow function syntax. I tried writing my own marcos, but I'm just failing spectacularly :P

**Comment by assertchris** [comment]
It's difficult to write these macros - don't be discouraged.

The problems is in how Yay works, not in the symbol we use here. Yay is essentially a `preg_replace` but with a pattern derived from tokens. There is some state machine stuff in there, but it is abstracted behind `·layer` which means we need to use delimiters to determine matching depth and enable recursion.

This is why a custom compiler function is required - so that we don't have to use `·layer` but can handle nesting.

**Comment by chris-kruining** [comment]
so basically, that which we want to achieve is not possible to achieve with yay? If so, maybe we could try to write a PHP extension that does something like taking in custom language patterns, so instead of a pre-compiler we 'extend' the actual compiler. Do you recon this might be a feasible strategy? If so, I might start looking into it :D

**Comment by assertchris** [comment]
I would prefer to still use the Pre infrastructure to kick the compilation off, since it's really easy to install Pre macros/compilers via Composer. https://github.com/preprocess/pre-phpx is an example of the kind of thing I'd suggest we try...

**Comment by chris-kruining** [comment]
I agree, the most important thing any modern php package imo must have is composer compatibility. (on a side node I was curios if php extensions could be managed via composer since you can list them as requirements, no, not directly, but [this](https://github.com/FriendsOfPHP/pickle) package seems to do it, haven't checked it out yet). I feel stupid for asking, but what does phpx do? could you give me an example, because it seems intriguing to me :D

**Comment by assertchris** [comment]
Here's an example repo: https://github.com/preprocess/example-phpx/blob/master/app/Component/TaskList.pre

![demo](https://github.com/preprocess/example-phpx/raw/master/demo.gif)

**Comment by chris-kruining** [comment]
oooh, so phpx is a total package off all the pre packages?

**Comment by assertchris** [comment]
Not exactly. It's an example of a naive compiler, to enable JSX-like syntax (or XHP if you are more familiar with that) to PHP. It uses some of the Pre macros, but it is the best example of how to register a custom compiler in the Pre tooling.

Edit: you can find a tutorial, for how that compiler is built, at https://www.sitepoint.com/reactjs-php-writing-compilers-easy-fun/

**Comment by chris-kruining** [comment]
aah I see, I wasn't familiar with either JSX or XHP. Unless I'm missing some clues, and all I'm doing is some brainstorming, as long as we stay in php we are kind of limited to creating glorified `preg_replace` functions are we not? So could it be possible to extend/fork yay to implement broader syntax parsing? Should I ask the yay repo how they would create a macro for this use case, may it is possible in yay but be simply don't understand it thoroughly enough?

**Comment by assertchris** [comment]
`preg_replace` isn't all we're limited to. In fact, the reason I made Phpx have its own compiler was to get around the state machine limitations of the Yay macro syntax. That's not to say that one couldn't build a custom compiler function in the middle of a macro - this is also possible. 

I'd indeed be curious to see how Márcio would solve this problem, but I suspect it's with a custom compiler function (or an `·expression` matcher)... ;)

Edit: I've pinged Márcio, on Twitter, so he'll be along as soon as is convenient.

**Comment by marcioAlmada** [comment]
/me pings - indeed to easily match a short closure body without a "layer" delimiter like `{}`,  you would need the mythical `·expression()` matcher https://github.com/marcioAlmada/yay/issues/43#issuecomment-341118074

**Comment by alepeino** [comment]
I created this as a starting point https://github.com/alepeino/pre-shorter-closures

Notice the Composer dependency (I'm requiring MarcelloDuarte's fork, because of the expression parser). It's still incomplete (I submitted a PR which would make the current failing test pass), however there's much more to do.

Also, if there are no `()` or `{}` in `(args) => {return value}` (meaning, if we want to support `$x => $x + 1`), I guess another symbol will definitively be needed, because that chain would not be different from a $key => $value pair in an array literal.

**Comment by marcioAlmada** [comment]
@alepeino YAY's parsec library was designed to support ambiguity, because of cases you may need to declare a syntax that clashes with already valid constructs, but it's a good practice to avoid it for possible core language polyfill. A good reference is Hacklang using a fat arrow `==>` for their short closures :wink:

**Comment by chris-kruining** [comment]
@alepeino `=>` not only applies to to array literals, but also to foreach'es and key-value yields in generators :P. So I fully agree on `==>` and can see the elegance in it.

**Comment by marcioAlmada** [comment]
Me pings @assertchris,

Heh, it took a while for me to have some free time to implement this correctly. But perhaps the [ExpressionParser](https://github.com/marcioAlmada/yay/blob/feature/expression%2Boperator_precedence/src/ExpressionParser.php) should be enough to close this request. You can refer to marcioAlmada/yay@2ff980b7ad4496f21059cff30050188976c5ab02 for a real-world-ish working example of arrow functions.

The __YAY__ version is resting on this branch while being tested:
> https://github.com/marcioAlmada/yay/tree/feature/expression+operator_precedence

Cheers 😅

**Comment by assertchris** [comment]
@marcioAlmada this is so exciting!

**Comment by chris-kruining** [comment]
@marcioAlmada Exiting indeed!!! This might mean the lib is a step closer to try out production code, I'll fiddle around with it soon, I would LOVE to have enums and arrow functions :D

**Comment by assertchris** [comment]
@chris-kruining if you require `"pre-short-closures": "dev-feature/expressions"` then you can try [this syntax](https://twitter.com/assertchris/status/963315301147447296)...

**Comment by chris-kruining** [comment]
@assertchris Yeah, I noticed, commented to quick :P it has been a while. Does this yay patch also mean that this feature request is fulfilled or do you still need to update some stuf?

**Comment by assertchris** [comment]
@chris-kruining it's not in the master branch yet (and won't be until it is based on a tagged version of Yay), so I'd keep this open for now...

**Comment by marcioAlmada** [comment]
The fuzz testing still needs improvements - feeding the parser random expressions - to see if things like operator precedence and edge cases are identical to PHP itself. Then, it can go to master. I'm being extra careful so we can have support for custom operators and AST visitors soon. It won't take so long I guess.

**Comment by chris-kruining** [comment]
@marcioAlmada does custom operators by any chance also include operator overloading?

**Comment by marcioAlmada** [comment]
@chris-kruining If you meant in the fashion of https://github.com/php/pecl-php-operator the answer is no, for now. I don't even think it's possible to implement this on a preprocess step. But we can discuss this on a separate issue if you have any ideas.

**Comment by chris-kruining** [comment]
this issue seems resolved to me, so closing it
